### ISSUE TITLE
Touchpad two finger scroll not working

### ISSUE THREAD

**Issue by sund3RRR** [hugopl/rtfm#5]
Touchpad two finger scroll not working.

**Comment by hugopl** [comment]
It works here, however the mouse cursor needs to be over the webview, I guess this is the default GTK behavior for touchpad two finger scroll.

Did you tested with the mouse over the webview?

**Comment by sund3RRR** [comment]
Hmm, i did some tests. I found this issue while packaging `rtfm` in `nixpkgs`, but it is not working only on non-NixOS system (debian 12). Maybe because of this errors in terminal (specific on non-NixOS systems using nix):
```bash
Gsk-Message: 21:25:47.243: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandPopup': Failed to create EGL display

Cannot get default EGL display: EGL_BAD_PARAMETER
PlatformDisplayLibWPE: could not create the EGL display: EGL_SUCCESS.
Cannot get default EGL display: EGL_BAD_PARAMETER
PlatformDisplayLibWPE: could not create the EGL display: EGL_SUCCESS.

```

Now i run this package on my QEMU NixOS VM and two finger scroll really works.
It is a very strange issue, because i can scroll in the search panel, but can't scroll the html page.

Sorry for the fake call, it can be problem on nix side, need to figure it out.
